### ISSUE TITLE
Getting module initialization error: TypeError

### ISSUE THREAD

**Issue by bart** [AnomalyInnovations/serverless-bundle#11]
I'm trying to use the `serverless-bundle` plugin on a sample project which runs a nuxt.js app as a serverless app. It's a pretty simple app which can be found here: https://github.com/serverless/examples/tree/master/aws-node-vue-nuxt-ssr

Without `serverless-bundle` it's working. Any idea what the reason could be? Unfortunately I'm not getting any additional information from Cloudwatch - just the error `module initialization error: TypeError`

Thanks

**Comment by bart** [comment]
All right, figured out a bit more with AWS X-Ray: The complete error message is: TypeError: Cannot assign to read only property 'exports' which might be an issue with mixing import/export with require statements, right? Any solution for that (I mean especially when using lots of 3rd party packages like we do here)?

**Comment by jayair** [comment]
Hmm can you point me to the file and line number that's causing the error?

**Comment by bart** [comment]
Unfortunately I'm not able to give you a line number. It's the lambda file (index.js) file that gets generated when doing `npm run deploy` on the project I posted above. I found the following stackoverflow post about it and will try to set some customs params in the serverless.yml that will hopefully fix the issue: https://github.com/webpack/webpack/issues/4039#issuecomment-419284940

**Comment by bart** [comment]
Short update: After directly including data from `binaryMimeTypes.js` into `index.js` I'm getting a new error:

```
Error: ENOENT: no such file or directory, open '/resources/error.mustache'",
  'at Object.openSync (fs.js:447:3)',
  'at Object.readFileSync (fs.js:349:35)',
  'at Object.<anonymous> (/Users/bart/Code/aws-node-vue-nuxt-ssr/.webpack/service/webpack:/Users/bart/Code/aws-node-vue-nuxt-ssr/node_modules/@nuxtjs/youch/src/Youch/index.js:20:1)',
  'at Object.../../@nuxtjs/youch/src/Youch/index.js (/Users/bart/Code/aws-node-vue-nuxt-ssr/.webpack/service/index.js:11865:30)',
  'at __webpack_require__ (/Users/bart/Code/aws-node-vue-nuxt-ssr/.webpack/service/webpack:/webpack/bootstrap:19:1)',
...
```

**Comment by jayair** [comment]
Thanks for the details. I'll have a look at this soon.

**Comment by jayair** [comment]
I'm looking at https://github.com/serverless/examples/tree/master/aws-node-vue-nuxt-ssr, it doesn't seem like it was using Webpack to bundle your Lambdas to begin with. I don't think serverless-bundle will work here. I'm not too familiar with Nuxt but I'm assuming they are packaging it themselves?
