### ISSUE TITLE
Missing eslint-plugin-jest

### ISSUE THREAD

**Issue by KinnersleyM** [AnomalyInnovations/serverless-bundle#111]
Any time I have tried to use serverless-bundle and run `sls deploy -V`, I seem to get an error saying:

```
ERROR in <my-dir>/starter-temp/handler.js
Module build failed (from ../node_modules/eslint-loader/index.js):
Error: Failed to load plugin jest: Cannot find module 'eslint-plugin-jest'
```

I can then get it working by installing eslint and eslint-plugin-jest afterwards. I uninstalled node, nvm and yarn from my computer but to no avail.

It isn't a huge problem as it can be fixed but it is annoying as I want to use serverless-bundle with no other addons and zero-config.

If anyone has had a similar issue let me know if it is something to do with my setup or not.

My package.json:

```
{
  "name": "starter-temp",
  "version": "1.1.0",
  "description": "A Node.js starter for the Serverless Framework with async/await and unit test support",
  "main": "handler.js",
  "scripts": {
    "test": "serverless-bundle test"
  },
  "author": "",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/AnomalyInnovations/serverless-nodejs-starter.git"
  },
  "devDependencies": {
    "serverless-bundle": "^1.2.5",
    "serverless-dotenv-plugin": "^2.1.1",
    "serverless-offline": "^5.3.3"
  }
}
```

my serverless.yml:
```
# NOTE: update this with your service name
service: starter-temp

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
```
Full error stack
```
Require stack:
- <my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config/plugins.js
- <my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config.js
-<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/cli-engine.js
- <my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/api.js
- <my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint-loader/index.js
- <my-dir>/starter-temp/node_modules/loader-runner/lib/loadLoader.js
- <my-dir>/starter-temp/node_modules/loader-runner/lib/LoaderRunner.js
- <my-dir>/starter-temp/node_modules/webpack/lib/NormalModule.js
- <my-dir>/starter-temp/node_modules/webpack/lib/NormalModuleFactory.js
- <my-dir>/starter-temp/node_modules/webpack/lib/Compiler.js
- <my-dir>/starter-temp/node_modules/webpack/lib/webpack.js
- <my-dir>/starter-temp/node_modules/serverless-webpack/lib/compile.js
- <my-dir>/starter-temp/node_modules/serverless-webpack/index.js
- <my-dir>/starter-temp/node_modules/serverless-bundle/index.js
- /Users/<home-dir>/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js
- /Users/<home-dir>/.config/yarn/global/node_modules/serverless/lib/Serverless.js
- /Users/<home-dir>/.config/yarn/global/node_modules/serverless/lib/utils/autocomplete.js
- /Users/<home-dir>/.config/yarn/global/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at Plugins.load (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config/plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config/plugins.js:165:21)
    at loadFromDisk (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config/config-file.js:529:35)
    at Object.load (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/config.js:342:29)
    at processText (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint-loader/index.js:278:17)
    at Object.module.exports (<my-dir>/starter-temp/node_modules/serverless-bundle/node_modules/eslint-loader/index.js:273:21)
 
  Error --------------------------------------------------
 
  Error: Webpack compilation error, see above
      at <my-dir>/starter-temp/node_modules/serverless-webpack/lib/compile.js:36:17
      at arrayEach (<my-dir>/starter-temp/node_modules/lodash/lodash.js:516:11)
      at Function.forEach (<my-dir>/starter-temp/node_modules/lodash/lodash.js:9342:14)
      at <my-dir>/starter-temp/node_modules/serverless-webpack/lib/compile.js:29:9
      at tryCatcher (<my-dir>/starter-temp/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (<my-dir>/starter-temp/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (<my-dir>/starter-temp/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (<my-dir>/starter-temp/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (<my-dir>/starter-temp/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (<my-dir>/starter-temp/node_modules/bluebird/js/release/promise.js:673:18)
      at <my-dir>/starter-temp/node_modules/bluebird/js/release/nodeback.js:42:21
      at finalCallback (<my-dir>/starter-temp/node_modules/webpack/lib/MultiCompiler.js:254:12)
      at <my-dir>/starter-temp/node_modules/webpack/lib/MultiCompiler.js:277:6
      at done (<my-dir>/starter-temp/node_modules/neo-async/async.js:2931:13)
      at runCompilers (<my-dir>/starter-temp/node_modules/webpack/lib/MultiCompiler.js:181:48)
      at <my-dir>/starter-temp/node_modules/webpack/lib/MultiCompiler.js:188:7
      at <my-dir>/starter-temp/node_modules/webpack/lib/MultiCompiler.js:270:7
      at finalCallback (<my-dir>/starter-temp/node_modules/webpack/lib/Compiler.js:257:39)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compiler.js:273:13
      at AsyncSeriesHook.eval [as callAsync] (eval at create (<my-dir>/starter-temp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at AsyncSeriesHook.lazyCompileHook (<my-dir>/starter-temp/node_modules/tapable/lib/Hook.js:154:20)
      at onCompiled (<my-dir>/starter-temp/node_modules/webpack/lib/Compiler.js:271:21)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compiler.js:681:15
      at AsyncSeriesHook.eval [as callAsync] (eval at create (<my-dir>/starter-temp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
      at AsyncSeriesHook.lazyCompileHook (<my-dir>/starter-temp/node_modules/tapable/lib/Hook.js:154:20)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compiler.js:678:31
      at AsyncSeriesHook.eval [as callAsync] (eval at create (<my-dir>/starter-temp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
      at AsyncSeriesHook.lazyCompileHook (<my-dir>/starter-temp/node_modules/tapable/lib/Hook.js:154:20)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compilation.js:1423:35
      at AsyncSeriesHook.eval [as callAsync] (eval at create (<my-dir>/starter-temp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
      at AsyncSeriesHook.lazyCompileHook (<my-dir>/starter-temp/node_modules/tapable/lib/Hook.js:154:20)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compilation.js:1414:32
      at AsyncSeriesHook.eval [as callAsync] (eval at create (<my-dir>/starter-temp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
      at AsyncSeriesHook.lazyCompileHook (<my-dir>/starter-temp/node_modules/tapable/lib/Hook.js:154:20)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compilation.js:1409:36
      at AsyncSeriesHook.eval [as callAsync] (eval at create (<my-dir>/starter-temp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
      at AsyncSeriesHook.lazyCompileHook (<my-dir>/starter-temp/node_modules/tapable/lib/Hook.js:154:20)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compilation.js:1405:32
      at AsyncSeriesHook.eval [as callAsync] (eval at create (<my-dir>/starter-temp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
      at AsyncSeriesHook.lazyCompileHook (<my-dir>/starter-temp/node_modules/tapable/lib/Hook.js:154:20)
      at Compilation.seal (<my-dir>/starter-temp/node_modules/webpack/lib/Compilation.js:1342:27)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compiler.js:675:18
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compilation.js:1261:4
      at AsyncSeriesHook.eval [as callAsync] (eval at create (<my-dir>/starter-temp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
      at AsyncSeriesHook.lazyCompileHook (<my-dir>/starter-temp/node_modules/tapable/lib/Hook.js:154:20)
      at Compilation.finish (<my-dir>/starter-temp/node_modules/webpack/lib/Compilation.js:1253:28)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compiler.js:672:17
      at eval (eval at create (<my-dir>/starter-temp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compilation.js:1185:12
      at <my-dir>/starter-temp/node_modules/webpack/lib/Compilation.js:1097:9
      at processTicksAndRejections (internal/process/task_queues.js:79:11)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.2
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.11
```

**Comment by jayair** [comment]
That's really weird. Your setup is almost exactly like this:

https://github.com/AnomalyInnovations/serverless-nodejs-starter

Can you try forking that repo and seeing if you get the same error? Because we use that exact one in the tutorial and it works fine.
