### ISSUE TITLE
Unable to run `package` or `deploy` using Typescript

### ISSUE THREAD

**Issue by justindra** [AnomalyInnovations/serverless-bundle#141]
I am unable to use the TypeScript configuration. It seems to keep failing when bundling. As an example I copied the test-case in 'tests/typescript` and adjusted it to have TS-only terms, e.g. classes.

The output is as follows:
```console
Serverless: Bundling with Webpack...
Starting type checking service... 
internal/modules/cjs/loader.js:967
  throw err;
  ^
Error: Cannot find module '/home/justin/projects/sls-bundle-typescript/--max-old-space-size=2048'
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
  at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
  at Function.Module._load (internal/modules/cjs/loader.js:840:27)
  at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
  at internal/main/run_main_module.js:17:47 {
    code: 'MODULE_NOT_FOUND',
    requireStack: []
  }
```

I've created a sample repo here:
https://github.com/justindra/serverless-bundle-typescript-issue

To get the error:
* `sls package` or `sls deploy`

**Comment by justindra** [comment]
I've been messing around with the plugin locally and what seems to fix it is removing the `ForkTsCheckerWebpackPlugin`. So I guess the issue could be with that somewhere?

**Comment by jayair** [comment]
We have a starter that you can use as an example — https://github.com/AnomalyInnovations/serverless-typescript-starter

**Comment by davidboom95** [comment]
The starter has the same problem too.

**Comment by justindra** [comment]
Yep, agree with @davidboom95 starter also has the same issue.

**Comment by joaodfmota** [comment]
I don't know why, but using yarn here it works 🤔

```JSON
"scripts": {
    "deploy": "serverless deploy",
    "start": "serverless offline start",
    "test": "serverless-bundle test"
  },
```
Error:
```npm start```
Work:
```yarn start```

**Comment by jayair** [comment]
What's the issue with starter and how do I replicate it?
