### ISSUE TITLE
esponse_lib_1.fail is not a function when I use option sourcemaps equal true

### ISSUE THREAD

**Issue by StErMi** [AnomalyInnovations/serverless-bundle#151]
Hi all,

the project is pretty simple as you can see 
![image](https://user-images.githubusercontent.com/146166/96093777-dd121880-0ecc-11eb-93ce-45bbe207452c.png)

if I set `sourcemaps` to `false` everything seems to work. If I set them to `true` I get this error when I open the URL created with `sls offline`

```
TypeError: response_lib_1.success is not a function
    at ../../../src/handler/sync.ts.exports.handle (/MY_PROJECT_FOLDER/.webpack/service/src/handler/webpack:/MY_PROJECT_FOLDER/src/handler/sync.ts:8:16)
    at InProcessRunner.run (/MY_PROJECT_FOLDER/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:178:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at LambdaFunction.runHandler (/MY_PROJECT_FOLDER/node_modules/serverless-offline/dist/lambda/LambdaFunction.js:325:20)
    at hapiHandler (/MY_PROJECT_FOLDER/node_modules/serverless-offline/dist/events/http/HttpServer.js:521:18)
    at module.exports.internals.Manager.execute (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/toolkit.js:45:28)
    at Object.internals.handler (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/request.js:312:32)
    at Request._execute (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/request.js:221:9)
TypeError: response_lib_1.fail is not a function
    at ../../../src/handler/sync.ts.exports.handle (/MY_PROJECT_FOLDER/.webpack/service/src/handler/webpack:/MY_PROJECT_FOLDER/src/handler/sync.ts:14:16)
    at InProcessRunner.run (/MY_PROJECT_FOLDER/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:178:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at LambdaFunction.runHandler (/MY_PROJECT_FOLDER/node_modules/serverless-offline/dist/lambda/LambdaFunction.js:325:20)
    at hapiHandler (/MY_PROJECT_FOLDER/node_modules/serverless-offline/dist/events/http/HttpServer.js:521:18)
    at module.exports.internals.Manager.execute (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/toolkit.js:45:28)
    at Object.internals.handler (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/request.js:312:32)
    at Request._execute (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/request.js:221:9)
offline: Failure: response_lib_1.fail is not a function
TypeError: response_lib_1.fail is not a function
    at ../../../src/handler/sync.ts.exports.handle (/MY_PROJECT_FOLDER/.webpack/service/src/handler/webpack:/MY_PROJECT_FOLDER/src/handler/sync.ts:14:16)
    at InProcessRunner.run (/MY_PROJECT_FOLDER/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:178:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at LambdaFunction.runHandler (/MY_PROJECT_FOLDER/node_modules/serverless-offline/dist/lambda/LambdaFunction.js:325:20)
    at hapiHandler (/MY_PROJECT_FOLDER/node_modules/serverless-offline/dist/events/http/HttpServer.js:521:18)
    at module.exports.internals.Manager.execute (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/toolkit.js:45:28)
    at Object.internals.handler (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/request.js:312:32)
    at Request._execute (/MY_PROJECT_FOLDER/node_modules/@hapi/hapi/lib/request.js:221:9)
```

how can I fix it?

**Comment by jayair** [comment]
It's being talked about here — https://github.com/AnomalyInnovations/serverless-bundle/issues/124

Closing this.
