### ISSUE TITLE
4.0.0+ missing many dependencies

### ISSUE THREAD

**Issue by jmparsons** [AnomalyInnovations/serverless-bundle#175]
Building with 3.0+ works fine, but 4.0 on a mac non m1, I tried node version 10 and 12, both force me to include a ton of dependencies. All of the eslint, developit, prettier, sinon etc.

**Comment by jayair** [comment]
Hi there, what do you mean it forced you to include them? Can you share some logs?

**Comment by jwelmac** [comment]
Hey @jayair,
I am having a similar issue which is fixed by using version `3.2.1`.

Here are some logs from my end.
```
$ serverless offline
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: DOTENV: Loading environment variables from .env, .env.development:
Serverless:      - AWS_ACCESS_KEY_ID
Serverless:      - AWS_SECRET_ACCESS_KEY
Serverless:      - DBNAME
Serverless:      - PASSWORD
Serverless:      - USERNAME
Serverless:      - ENDPOINT
Serverless:      - GQL_HOST
Serverless:      - GQL_REGION
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Bundling with Webpack...
 
  Error --------------------------------------------------
 
  Error: Failed to load config "medikoo" to extend from.
  Referenced from: [working_directory]/node_modules/2-thenable/package.json
      at configMissingError ([working_directory]/node_modules/@eslint/eslintrc/lib/config-array-factory.js:289:9)
      at ConfigArrayFactory._loadExtendedShareableConfig ([working_directory]/node_modules/@eslint/eslintrc/lib/config-array-factory.js:877:23)
      at ConfigArrayFactory._loadExtends ([working_directory]/node_modules/@eslint/eslintrc/lib/config-array-factory.js:780:25)
      at ConfigArrayFactory._normalizeObjectConfigDataBody ([working_directory]/node_modules/@eslint/eslintrc/lib/config-array-factory.js:719:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData ([working_directory]/node_modules/@eslint/eslintrc/lib/config-array-factory.js:664:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory.loadInDirectory ([working_directory]/node_modules/@eslint/eslintrc/lib/config-array-factory.js:510:28)
      at CascadingConfigArrayFactory._loadConfigInAncestors ([working_directory]/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
      at CascadingConfigArrayFactory.getConfigArrayForFile ([working_directory]/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:300:18)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.2
     Framework Version:         2.17.0 (local)
     Plugin Version:            4.4.1
     SDK Version:               2.3.2
     Components Version:        3.4.3
 
 ----- package.json ----
 ...
 "dependencies": {
    "aws-appsync": "4.0.1",
    "graphql-tag": "2.11.0",
    "mysql": "2.18.1"
  },
  "devDependencies": {
    "@serverless/typescript": "2.16.1",
    "@types/aws-lambda": "8.10.68",
    "@types/mysql": "2.15.17",
    "@types/node": "14.14.19",
    "serverless": "2.17.0",
    "serverless-bundle": "4.1.0",
    "serverless-dotenv-plugin": "3.1.0",
    "serverless-offline": "6.8.0",
    "webpack": "4.44.2"
  }

  --- serverless.ts ---
  ...
   custom: {
    bundle: {
      sourcemaps: true,
      linting: true,
      caching: false
    }
  },
  package: {
    individually: true
  },
  plugins: [
    "serverless-bundle",
    "serverless-offline",
    "serverless-dotenv-plugin"
  ],
```

In an attempt to fix this issue I find myself going down a rabbit hole of dependency installations.

**Comment by rcoundon** [comment]
I'm also seeing the error with version 4.1.0

Error: Failed to load config "medikoo" to extend from.

**Comment by mattcwill** [comment]
I get the "Failed to load config "medikoo" to extend from" error with 4.1.0 as well. I don't get the error with 4.0.1. For what it's worth my Serverless version is 2.17.0 and I am using Typescript.

**Comment by teban3010** [comment]
I "fixed" it by adding the following configuration on `serverles.yaml`:

``` yaml
custom:
  bundle:
    linting: false # Enable linting as a part of the build process
```

As I have eslint configured with my own rules, running the lint command works as expected, and with that I don't see any error when runing `serverless offline` or `serverless deploy`.

I tried to install `medikoo` but as mentioned before, after that there are a lot more to install, all related to eslint.

**Comment by itskemo** [comment]
Complete error log:


```
  Error: Failed to load config "medikoo" to extend from.
  Referenced from: /Volumes/Development/Services/<removed>/node_modules/2-thenable/package.json
      at configInvalidError (/Volumes/Development/Services/<removed>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
      at ConfigArrayFactory._loadExtendedShareableConfig (/Volumes/Development/Services/<removed>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
      at ConfigArrayFactory._loadExtends (/Volumes/Development/Services/<removed>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/Volumes/Development/Services/<removed>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/Volumes/Development/Services/<removed>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory.loadInDirectory (/Volumes/Development/Services/<removed>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
      at CascadingConfigArrayFactory._loadConfigInAncestors (/Volumes/Development/Services/<removed>/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
      at CascadingConfigArrayFactory.getConfigArrayForFile (/Volumes/Development/Services/<removed>/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:300:18)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.20.0
     Framework Version:         1.83.2 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
```

**Comment by mkherlakian** [comment]
I'm also experiencing this issue on 4.2.1
This is for a Typescript based project, I have a `tsconfig.json` file in the root of the project, otherwise all defaults.

I tried to go down the dep tree by just deploying and adding missing deps, I stopped after about 20 of them (in case this helps to fix)

```
    "@brettz9/eslint-plugin": "^1.0.3",
    "@ljharb/eslint-config": "^17.5.1",
    "eslint-config-ash-nazg": "^29.2.0",
    "eslint-config-bliss": "^5.0.0",
    "eslint-config-developit": "^1.2.0",
    "eslint-config-dustinspecker": "^5.0.0",
    "eslint-config-google": "^0.14.0",
    "eslint-config-jsdoc": "^15.4.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-config-sinon": "^4.0.0",
    "eslint-config-standard": "^16.0.2",
    "eslint-plugin-array-func": "^3.1.7",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "eslint-plugin-html": "^6.1.1",
    "eslint-plugin-ie11": "^1.0.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsdoc": "^32.0.2",
    "eslint-plugin-markdown": "^2.0.0",
    "eslint-plugin-no-unsanitized": "^3.1.4",
    "eslint-plugin-no-use-extend-native": "^0.5.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-promise": "^4.3.1",
    "eslint-plugin-radar": "^0.2.1",
    "eslint-plugin-unicorn": "^28.0.2",
```

As the linter was still complaining...

**Comment by jayair** [comment]
I think this might be an issue with eslint picking up the wrong config, as it goes up the directories. Can I bother somebody for a simple repo with the issue? I'll need to take a deeper look.

**Comment by mkherlakian** [comment]
@jayair Here's one: https://github.com/mkherlakian/serverlessBundleApi

Any `serverless` command should result in the error documented below. Let me know if I can do anything else to help.
