### ISSUE TITLE
bundling mjml and its dependencies cause Error: Cannot find module '../lib/utils.js'

### ISSUE THREAD

**Issue by fusionbeam** [AnomalyInnovations/serverless-bundle#182]
I'm trying to bundle a lambda that is dependent on package mjml (and its dependencies).
( using "serverless-bundle": "^4.1.0") 
my dependencies are: 
```
"dependencies": {
    "aws-arn-parser": "1.0.1",
    "aws-sdk": "^2.816.0",
    "js-base64": "^2.5.1",
    "mjml": "^4.7.1",
    "node-fetch": "^2.3.0"
  },
```

have tried force including mjml without success.

The error I get when lambda is executed is:
```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module '../lib/utils.js'",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module '../lib/utils.js'",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
    "    at Module.load (internal/modules/cjs/loader.js:879:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```

**Comment by jayair** [comment]
What is the `lib/util.js` that it is referencing? Is that a part of your Lambda code?

**Comment by thomaschaaf** [comment]
Using mjml works fine for me. So this must be in your own code.
