### ISSUE TITLE
Lint fails with "failed to load config medikoo" and breaks packaging

### ISSUE THREAD

**Issue by henhal** [AnomalyInnovations/serverless-bundle#216]
```
Error ---------------------------------------------------
 
  Error: Failed to load config "medikoo" to extend from.
  Referenced from: /snip/node_modules/2-thenable/package.json
      at configInvalidError (/snip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
      at ConfigArrayFactory._loadExtendedShareableConfig (/snip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
      at ConfigArrayFactory._loadExtends (/snip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/snip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
```

I set up a new module with latest serverless and serverless-bundle, and when calling `sls package` I get the above error. If using `linting: false` I can bypass it, but I don't understand why eslint requires medikoo.

These are the only modules I find referring to medikoo:
```
$ find node_modules -type f -name ".eslint*" | xargs grep medikoo
node_modules/ncjsm/is-module-not-found-error/.eslintrc.json:{ "extends": "medikoo/es3", "root": true }
node_modules/ncjsm/get-resolver/.eslintrc.json:	"extends": "medikoo/es3",
node_modules/ncjsm/require-uncached/.eslintrc.json:{ "extends": "medikoo/es5", "root": true }
```

Also, running `eslint` separately works fine.

**Comment by sdornan** [comment]
Same issue here, and I don't _want_ to turn off the linting.

**Comment by ipatka** [comment]
Works if you downgrade to Serverless-bundle @3.2.1
