### ISSUE TITLE
Default assignment while destructuing

### ISSUE THREAD

**Issue by techterbium** [AnomalyInnovations/serverless-bundle#25]
I am using serverless-bundle to webpack my function and I am seeing below issue when running the lambda on AWS. 
**Code:**
`async (event, context,callback) => {
  const { queryStringParameters = {} } = event;
  const { name = '' } = queryStringParameters;
`

this is failing when deployed and ran on AWS lambda, but not locally. 

**Error message**:

{
    "errorType": "TypeError",
    "errorMessage": "Cannot destructure property `name` of 'undefined' or 'null'.",
    "stack": [
        "TypeError: Cannot destructure property `name` of 'undefined' or 'null'.",
        "    at Runtime.getSubscriber [as handler] (/var/task/handlers/webpack:/Users/username/servicename/handlers/subscribers.js:6:25)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
    ]
}

Thanks for this very useful plugin.

**Comment by jayair** [comment]
Oh interesting. Which version of Node are you using locally? And whats the Node version for your Lambda?
