### ISSUE TITLE
Webpack validation error

### ISSUE THREAD

**Issue by ghostnumber7** [AnomalyInnovations/serverless-bundle#264]
A new [webpack version](https://github.com/webpack/webpack/releases/tag/v5.53.0) as just released, which makes bundle fail [here](https://github.com/AnomalyInnovations/serverless-bundle/blob/master/src/webpack.config.js#L370) with the following error: 
```shell
Serverless: Could not load webpack config '/Users/mgodoy/project/serverless-bundle/src/webpack.config.js'
 
 Validation Error ----------------------------------------
 
  ValidationError: Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.
   - options should be one of these:
     object { resourceRegExp, contextRegExp? } | object { checkResource }
     Details:
      * options misses the property 'resourceRegExp'. Should be:
        RegExp
        -> A RegExp to test the request against.
      * options misses the property 'checkResource'. Should be:
        function
        -> A filter function for resource and context.
      at validate (/Users/mgodoy/project/serverless-bundle/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
      at /Users/mgodoy/project/serverless-bundle/node_modules/webpack/lib/util/create-schema-validation.js:16:17
      at new IgnorePlugin (/Users/mgodoy/project/serverless-bundle/node_modules/webpack/lib/IgnorePlugin.js:28:3)
      at plugins (/Users/mgodoy/project/serverless-bundle/src/webpack.config.js:370:16)
      at Object.<anonymous> (/Users/mgodoy/project/serverless-bundle/src/webpack.config.js:452:12)
      at Module._compile (internal/modules/cjs/loader.js:1072:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
      at Module.load (internal/modules/cjs/loader.js:937:32)
      at Function.Module._load (internal/modules/cjs/loader.js:778:12)
      at Module.require (internal/modules/cjs/loader.js:961:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at ServerlessPlugin.validate (/Users/mgodoy/project/serverless-bundle/node_modules/serverless-webpack/lib/validate.js:152:31)
      at ServerlessPlugin.tryCatcher (/Users/mgodoy/project/serverless-bundle/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/mgodoy/project/serverless-bundle/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/mgodoy/project/serverless-bundle/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/Users/mgodoy/project/serverless-bundle/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/Users/mgodoy/project/serverless-bundle/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/Users/mgodoy/project/serverless-bundle/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/mgodoy/project/serverless-bundle/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/mgodoy/project/serverless-bundle/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by JBoetzkes** [comment]
I am getting the same issue with serverless bundle 5.0.1

**Comment by ekremkenter** [comment]
Anyone with any fixes or a way to avoid that?

**Comment by rogueturnip** [comment]
easiest fix is to revert to 4.4.0 until a new release.

**Comment by jayair** [comment]
Published https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v5.0.2

**Comment by ghostnumber7** [comment]
Thanks :)

**Comment by bernier** [comment]
Looks like a duplicate of the issue I opened back in August https://github.com/AnomalyInnovations/serverless-bundle/issues/259 but that one seems to have more visibility.

I tried upgrading to 5.0.2 but I'm still having the same issue, anyone was able to solve it?

**Comment by knvpk** [comment]
Im using master and still getting this error.

**Comment by knvpk** [comment]
> Looks like a duplicate of the issue I opened back in August #259 but that one seems to have more visibility.
> 
> I tried upgrading to 5.0.2 but I'm still having the same issue, anyone was able to solve it?

yes with 5.0.2 also still issue exists.
