### ISSUE TITLE
flaky webpack compilation error 

### ISSUE THREAD

**Issue by mishabruml** [AnomalyInnovations/serverless-bundle#285]
I get this error transiently (not consistently; sometimes build passes) with 
serverless 2.64.1
serverless-bundle: ^5.2.0

```
serverless-bundle: CommonJS, ES3, or ES5 are not supported
Serverless: Bundling with Webpack...
ERROR in ../../../packages/service-a/src/handlers/hello/index.ts
Module build failed (from ../node_modules/ts-loader/index.js):
Error: Not implemented
    at Object.notImplemented (/Users/mishabruml/hm/****/node_modules/typescript/lib/typescript.js:1774:15)
    at createBuilderProgramWithReferences (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/servicesHost.js:283:50)
    at createNewProgram (/Users/mishabruml/hm/****/node_modules/typescript/lib/typescript.js:120547:30)
    at synchronizeProgram (/Users/mishabruml/hm/****/node_modules/typescript/lib/typescript.js:120526:17)
    at Object.createWatchProgram (/Users/mishabruml/hm/****/node_modules/typescript/lib/typescript.js:120449:9)
    at Object.initializeInstance (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/instances.js:278:73)
    at successLoader (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/index.js:26:17)
    at Object.loader (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/index.js:23:5)

webpack compiled with 1 error
ERROR in ../../../packages/service-a/src/handlers/accountStateConsumer/index.ts
Module build failed (from ../node_modules/ts-loader/index.js):
TypeError: Cannot read properties of null (reading 'getProgram')
    at Object.getEmitOutput (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/instances.js:514:41)
    at getEmit (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/index.js:262:37)
    at successLoader (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/index.js:39:11)
    at Object.loader (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/index.js:23:5)

webpack compiled with 1 error
ERROR in ../../../packages/service-a/src/handlers/postMoveOut/index.ts
Module build failed (from ../node_modules/ts-loader/index.js):
TypeError: Cannot read properties of null (reading 'getProgram')
    at Object.getEmitOutput (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/instances.js:514:41)
    at getEmit (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/index.js:262:37)
    at successLoader (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/index.js:39:11)
    at Object.loader (/Users/mishabruml/hm/****/node_modules/serverless-bundle/node_modules/ts-loader/dist/index.js:23:5)

webpack compiled with 1 error
```

**Comment by nicgordon** [comment]
Same here @darbio. Did you find a solution to this?
