### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by Vadorequest** [AnomalyInnovations/serverless-bundle#3]
It doesn't seem like serverless-bundle is compatible with jest

```
 FAIL  src/functions/refresh-cache.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/vadorequest/dev/cache-tfp/src/functions/refresh-cache.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { client, flushdb, getKey, getValue } from '../utils/redis';
                                                                                                    ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)

```

Using the same config as in https://github.com/AnomalyInnovations/serverless-bundle/issues/2

Should I use a custom .babelrc with jest support or something similar? Or a missing package like jest-babel?

**Comment by Vadorequest** [comment]
I tried reinstalling babel-jest `yarn add -D babel-jest` but it didn't fix the tests.

**Comment by Vadorequest** [comment]
My bad, I hadn't read the doc thoroughly enough: https://github.com/AnomalyInnovations/serverless-bundle#getting-started

Using 

```

    "test": "NODE_ENV=${NODE_ENV:-test}; yarn sls:dotenv && yarn delete:redis ; yarn start:redis:daemon && serverless-bundle test --watchAll --runInBand",
    "test:once": "NODE_ENV=${NODE_ENV:-test}; yarn sls:dotenv && yarn delete:redis ; yarn start:redis:daemon && serverless-bundle test",
    "test:coverage": "NODE_ENV=${NODE_ENV:-test}; yarn sls:dotenv && serverless-bundle test --coverage --runInBand"
```

Instead of 
```

    "test": "NODE_ENV=${NODE_ENV:-test}; yarn sls:dotenv && yarn delete:redis ; yarn start:redis:daemon && jest --watchAll --runInBand",
    "test:once": "NODE_ENV=${NODE_ENV:-test}; yarn sls:dotenv && yarn delete:redis ; yarn start:redis:daemon && jest",
    "test:coverage": "NODE_ENV=${NODE_ENV:-test}; yarn sls:dotenv && npx jest --coverage --runInBand"
```

Fixed it.
