### ISSUE TITLE
Unable to find package.json

### ISSUE THREAD

**Issue by clementAC** [AnomalyInnovations/serverless-bundle#63]
Hi,

After upgrading to 1.3.0, I'm unable to package lambda function. 

I have a global package.json on root and multiple services with their own serverless.yml. In order to deploy, I use the sls deploy command inside the correct service directory (or using seed services). In 1.3.0, serverless-bundle is looking in the service directory and not at root directory. It result in an error abording the bundle process.

```
Project
├── package.json
├── services
│   ├── service1
│   │   ├── serverless.yml
│   │   ├── handler.js
│   │── service2
│   │   ├── serverless.yml
│   │   ├── handler.js
```

**Comment by jayair** [comment]
@clementAC Thanks for bringing this up. I'm taking a look.

**Comment by jayair** [comment]
@clementAC I'm trying to replicate this and I couldn't. When you say:

> In 1.3.0, serverless-bundle is looking in the service directory and not at root directory.

What does that mean? Can you share what you are importing and the error you are getting?

**Comment by clementAC** [comment]
> >In 1.3.0, serverless-bundle is looking in the service directory and not at root directory.

>What does that mean? Can you share what you are importing and the error you are getting?
In version before 1.3.0 webpack and serverless-bundle took the only package.json in the project, the one at the root directory. In version 1.3.0, webpack and serverless bundle try to open a local package.json inside the service directory but it does not exists.

Here is the full error.
```
Error: ENOENT: no such file or directory, open 'path\to\project\services\licence\package.json'
      at Object.openSync (fs.js:451:3)
      at Object.readFileSync (fs.js:353:35)
      at readFileSync (path\to\globalNpm\npm\node_modules\serverless\lib\utils\fs\readFileSync.js:7:24)
      at Utils.readFileSync (path\to\globalNpm\npm\node_modules\serverless\lib\classes\Utils.js:84:12)
      at path\to\project\node_modules\serverless-webpack\lib\packExternalModules.js:217:51
      at tryCatcher (path\to\project\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (path\to\project\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (path\to\project\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (path\to\project\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (path\to\project\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (path\to\project\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (path\to\project\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (path\to\project\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
```

the environment information  same error on Linux environment: 
```
 Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.11.1
     Framework Version:         1.58.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
    Serverless-bundle : 1.3.0
```
Custom section in serverless.yml
```
custom:
  bundle:
    sourcemaps: true
    packager: yarn
    ignorePackages:
      - pg-native
```
Reverting to previous serverless-bundle with the exact same configuration works.

**Comment by jayair** [comment]
@clementAC Thanks for the added info. I didn't realize that the issue was with the `serverless deploy` or `package` command.

Just pushed a fix for this. Try version 1.3.1.

**Comment by clementAC** [comment]
Perfect everything works now ! Pg-native module excluded, bundled under the right node version and packaged with yarn. Such a great work you do to simplify my life. Thank you.
