### ISSUE TITLE
Unexpected Webpack compilation error

### ISSUE THREAD

**Issue by eskonuutila** [AnomalyInnovations/serverless-bundle#95]
In `sls` commands `package` and `deploy`, compiling using Webpack fails with the following error message:

```
demo git:(exp) ✗ sls package
Serverless: Bundling with Webpack...

ERROR in /home/userx/demo/src/indexify.js
Module build failed (from /home/userx/demo/node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-transform-runtime' from '/home/userx/demo/src'
- Did you mean "@babel/transform-runtime"?
    at Function.resolveSync [as sync] (/home/userx/demo/node_modules/resolve/lib/sync.js:89:15)
    at resolveStandardizedName (/home/userx/demo/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/home/userx/demo/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/home/userx/demo/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/home/userx/demo/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /home/userx/demo/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/home/userx/demo/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/home/userx/demo/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/home/userx/demo/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
    at mergeChainOpts (/home/userx/demo/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /home/userx/demo/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at Generator.next (<anonymous>)
    at buildRootChain (/home/userx/demo/node_modules/@babel/core/lib/config/config-chain.js:120:29)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/home/userx/demo/node_modules/@babel/core/lib/config/partial.js:95:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at Function.<anonymous> (/home/userx/demo/node_modules/@babel/core/lib/config/partial.js:120:25)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/userx/demo/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/userx/demo/node_modules/gensync/index.js:84:14)
    at Object.<anonymous> (/home/userx/demo/node_modules/@babel/core/lib/config/index.js:41:61)
    at Object.<anonymous> (/home/userx/demo/node_modules/babel-loader/lib/index.js:151:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/userx/demo/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/home/userx/demo/node_modules/babel-loader/lib/index.js:5:194)
    at /home/userx/demo/node_modules/babel-loader/lib/index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/userx/demo/node_modules/babel-loader/lib/index.js:5:97)
    at Object._loader (/home/userx/demo/node_modules/babel-loader/lib/index.js:231:18)
    at Object.loader (/home/userx/demo/node_modules/babel-loader/lib/index.js:64:18)
    at Object.<anonymous> (/home/userx/demo/node_modules/babel-loader/lib/index.js:59:12)
 
  Error --------------------------------------------------
 
  Error: Webpack compilation error, see above
      at /home/userx/demo/node_modules/serverless-webpack/lib/compile.js:36:17
      at arrayEach (/home/userx/demo/node_modules/lodash/lodash.js:516:11)
      at Function.forEach (/home/userx/demo/node_modules/lodash/lodash.js:9342:14)
      at /home/userx/demo/node_modules/serverless-webpack/lib/compile.js:29:9
      at tryCatcher (/home/userx/demo/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/userx/demo/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/userx/demo/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/userx/demo/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/userx/demo/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/userx/demo/node_modules/bluebird/js/release/promise.js:673:18)
      at /home/userx/demo/node_modules/bluebird/js/release/nodeback.js:42:21
      at finalCallback (/home/userx/demo/node_modules/webpack/lib/Compiler.js:257:39)
      at /home/userx/demo/node_modules/webpack/lib/Compiler.js:273:13
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/userx/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/userx/demo/node_modules/tapable/lib/Hook.js:154:20)
      at onCompiled (/home/userx/demo/node_modules/webpack/lib/Compiler.js:271:21)
      at /home/userx/demo/node_modules/webpack/lib/Compiler.js:681:15
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/userx/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/userx/demo/node_modules/tapable/lib/Hook.js:154:20)
      at /home/userx/demo/node_modules/webpack/lib/Compiler.js:678:31
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/userx/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/userx/demo/node_modules/tapable/lib/Hook.js:154:20)
      at /home/userx/demo/node_modules/webpack/lib/Compilation.js:1423:35
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/userx/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/userx/demo/node_modules/tapable/lib/Hook.js:154:20)
      at /home/userx/demo/node_modules/webpack/lib/Compilation.js:1414:32
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/userx/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/userx/demo/node_modules/tapable/lib/Hook.js:154:20)
      at /home/userx/demo/node_modules/webpack/lib/Compilation.js:1409:36
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/userx/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/userx/demo/node_modules/tapable/lib/Hook.js:154:20)
      at /home/userx/demo/node_modules/webpack/lib/Compilation.js:1405:32
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/userx/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/userx/demo/node_modules/tapable/lib/Hook.js:154:20)
      at Compilation.seal (/home/userx/demo/node_modules/webpack/lib/Compilation.js:1342:27)
      at /home/userx/demo/node_modules/webpack/lib/Compiler.js:675:18
      at /home/userx/demo/node_modules/webpack/lib/Compilation.js:1261:4
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/userx/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
      at AsyncSeriesHook.lazyCompileHook (/home/userx/demo/node_modules/tapable/lib/Hook.js:154:20)
      at Compilation.finish (/home/userx/demo/node_modules/webpack/lib/Compilation.js:1253:28)
      at /home/userx/demo/node_modules/webpack/lib/Compiler.js:672:17
      at eval (eval at create (/home/userx/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
      at /home/userx/demo/node_modules/webpack/lib/Compilation.js:1185:12
      at /home/userx/demo/node_modules/webpack/lib/Compilation.js:1097:9
      at processTicksAndRejections (internal/process/task_queues.js:79:11)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.2.0
     Framework Version:         1.70.0
     Plugin Version:            3.6.11
     SDK Version:               2.3.0
     Components Version:        2.30.10


```

So it seems that webpack tries to use `babel-plugin-transform-runtime` instead of `@babel/transform-runtime`. Directory `node_modules/@babel` contains `plugin-transform-runtime` as well as several other plugins.

Below are my simple `package.json` and `serverless.yml` files. How can I fix this? Is there something else to check to find the error?

`package.json`:
```
{
  "name": "demo",
  "version": "1.1.0",
  "description": "A Node.js starter for the Serverless Framework with async/await and unit test support",
  "main": "handler.js",
  "scripts": {
    "test": "serverless-bundle test",
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/AnomalyInnovations/serverless-nodejs-starter.git"
  },
  "devDependencies": {
    "aws-sdk": "^2.673.0",
    "serverless-bundle": "^1.2.5",
    "serverless-dotenv-plugin": "^2.1.1",
    "serverless-offline": "^5.3.3"
  },
  "dependencies": {
    "uuid": "^7.0.3"
  }
}
```

`serverless.yml`:
```
service: demo

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

custom:
 stage: ${opt:stage, self:provider.stage}
 
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

functions:
  
  indexify:
    handler: src/indexify.main
```

**Comment by eskonuutila** [comment]
Here is `src/indexify.main`, which probably doesn't cause the error.

```
import md5 from 'md5';

export function success(body) {
    return buildResponse(200, body);
}

export function failure(body) {
    return buildResponse(500, body);
}

function buildResponse(statusCode, body) {
    return {
	statusCode: statusCode,
	headers: {
	    "Access-Control-Allow-Origin": "*",
	    "Access-Control-Allow-Credentials": true
	},
	body: JSON.stringify(body)
    };
}


module.exports.main = async(event, context, callback) => {
    try {
        callback(null, success(true));
    } catch(err) {
        console.error(`Failure: indexify raised an exception`, {err});
        callback(null, failure({status: false, error: err}));
    }
};

```

**Comment by jayair** [comment]
I notice you are using `v1.2.5`. Can you try it with the current version `v1.4.0`?
